### ISSUE TITLE
Readonly access and no-token mode

### ISSUE THREAD

**Issue by vors** [weswigham/GithubProvider#1]
Awesome project!

I would like to use it in read-only mode for few projects.

Main use case: I want to get some code on CI system, like `DscResource.Tests` here https://github.com/PowerShell/xExchange/blob/dev/appveyor.yml . If I can mount particular GitHub repo, instead of cloning it, it would be much nicer. For read-only mode I should not need a token.

**Comment by vors** [comment]
Hm, I guess without a token, I would hit 'Unauthorized API requests' limit pretty soon...
So, it's more about a 'demo mode' to provide people a sneak peek without asking for creating a token.

**Comment by weswigham** [comment]
I don't check permissions on my side, so simply providing an empty string in the `GITHUB_TOKEN` environment variable aught to work? I don't actually know, I've never actually tried. I did try changing the permissions on the token though, they works pretty okay if I recall correctly. The API error should happily propagate all the way up to the shell.

**Comment by vors** [comment]
Without setting up `$env:GITHUB_TOKEN` or with empty string, you get this error

```
PS GH:\> ls
ls : Value cannot be null.
Parameter name: token
At line:1 char:1
+ ls
+ ~~
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], ArgumentNullE
   xception
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShel
   l.Commands.GetChildItemCommand
```

The problem is not only in creating a more actionable error message. Token carries information about user identity, so you can start query GitHub API with something meanful for `ls`: user orgs. Without user name, the only reasonable thing to do would be query GitHub for all users / orgs, which is not the best expirience. On the other hand, if I know for sure that I want to browse `GH:\PowerShell` I can just cd there. So maybe `ls` can print out warning, when it expects tons of info and actually query it, if called with `-Force`:

```
GH:\> ls
WARNING: you are in the anonymous mode, Get-Item cannot identify relevant users and organizations for you.
Get-Item -Force will print all users and organizations on GitHub.
GH:\> ls -Force
...
```

**Comment by weswigham** [comment]
Hm, adding a more useful error message would certainly be helpful. I'll look into it.

**Comment by weswigham** [comment]
Querying all users/orgs for the root without auth doesn't make too much sense (there's too many, you'd hit the API limit trying to get them all, since they're paginated). I think a more sensible/instructive error is probably the best case.

**Comment by vors** [comment]
Agree. Btw, just found that I can `cd GH:\GitHub`. :+1:

**Comment by weswigham** [comment]
The provider now supports operation without a token - however you'll find that you run into your rate limit _very_ quickly.
