### ISSUE TITLE
Investigate why the out-file test is failing on AppVeyor

### ISSUE THREAD

**Issue by weswigham** [weswigham/GithubProvider#5]
It doesn't fail locally so it's a bit hard to reproduce exactly what's going on.

**Comment by vors** [comment]
There is a way to rdp to the worker machine: 

http://help.appveyor.com/discussions/questions/984-remote-to-the-worker-machine-and-install-software-with-reboot

Script location
https://github.com/appveyor/ci/blob/master/scripts/enable-rdp.ps1

**Comment by weswigham** [comment]
Fixed. There were two issues at play - first, a new version of pester started asking for encoding when comparing file contents, which the provider didn't support. Second, intermittent failures were caused due to github API propagation delay, so the test which did multiple dependent actions how has a delay, which has made it more consistently pass.
